### PR TITLE
Fix/cors connection

### LINKED ISSUE #32: CORS Connection Front-Back
ADD and SOLVE the CORS functionality.

### PR DESCRIPTION
**Pull request by amirmx2905**
ADDED CORS functionality and fixed some issued with run.zh

### CODE REVIEW

File: src/api/postRequests.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ export const postUserRequest = async (
   data: PostUserData
 ): Promise<ResponseData> => {
   try {
-    const response = await fetch(url + "/signup", {
+    const response = await fetch("http://localhost:3000/signup", {
```
Comment (cesarmendozav) [inline src/api/postRequests.ts]: It would be better to have the URL as a parameter instead of the hardcoded URL value, so it remains dynamic.

File: backend/src/connection.cpp [hunk 2]
```diff
@@ -1,152 +1,217 @@
...
+ 
+   // [CORS_CONFIG] - Configure Cross-Origin Resource Sharing
+   auto& cors = app.get_middleware<crow::CORSHandler>();
+   
+   // [CORS_CONFIG_DETAILS] - Properly configure CORS to allow requests from frontend
+   cors
+       .global()
+       .headers("Content-Type", "Authorization")
+       .methods("POST"_method, "GET"_method, "PUT"_method, "DELETE"_method, "OPTIONS"_method)
+       .origin("http://localhost:5173")
```
Comment (cesarmendozav) [inline backend/src/connection.cpp]: This configuration only allows requests from http://localhost:5173, which is fine for development purposes. However, in a production environment, hardcoding the origin might not be ideal. Ideally, you should consider allowing multiple origins or setting the origin dynamically based on the environment. For instance, you could have a configuration where the allowed origin is pulled from an environment variable or a list of trusted origins.

**Review by cesarmendozav — CHANGES_REQUESTED** [review]

**Review by cesarmendozav — APPROVED** [review]
I'm really proud of your work on this

**Review by JaimeTAR — APPROVED** [review]
Finally!!!!
